[DO NOT MERGE] Update to jfa 0.6.0
jasp-stats/jaspAudit pull request #139
Opened 2021-09-08 23:34 UTC by koenderks

2021-09-24 11:38 UTC, vandenman commented
@koenderks did you mean to assign reviewers already?

2021-09-24 12:59 UTC, Kucharssim commented
> did you mean to assign reviewers already?

Koen asked me originally, but I am happy if @FBartos review it instead!

2021-09-24 13:09 UTC, FBartos commented
well, I have 4 PRs to manage, so if you were planning to review it @Kucharssim it would be very appreciated :)

2021-09-27 10:23 UTC, koenderks commented
@vandenman @Kucharssim Yes, this is ready for review.

2021-09-28 15:03 UTC, vandenman requested changes
You changed quite a bunch of option names here. To guarantee backwards compatibility, you should also update Upgrader.qml.

I couldn't really find any bugs, but there are simply too many changes to carefully review all the code.

2021-10-03 17:24 UTC, koenderks commented
Some options have been removed (like number of items in planning), how can we indicate this in the upgrader?

2021-10-06 10:08 UTC, AlexanderLyNL commented on R/auditCommonFunctions.R
>        if (.jfaAuditRiskModelCalculation(options) >= 1) {
Why is this compared to 1?

2021-10-06 10:12 UTC, AlexanderLyNL commented on R/auditCommonFunctions.R
> +      dist <- switch(options[["likelihood"]],
distName (?) Here you're creating the name of the distribution to be used in the plot title.

2021-10-06 10:13 UTC, AlexanderLyNL commented on R/auditCommonFunctions.R
> +          ggplot2::annotate("text", y = k, x = length(n):1, label = k, size = 6, vjust = 0.5, hjust = -0.25) +
Why is the x-axis flipped? Going from n to 1?

2021-10-06 10:15 UTC, AlexanderLyNL commented on R/auditCommonFunctions.R
> +      errors <- state[["x"]]
The naming "x" is rather elusive.

2021-10-06 10:16 UTC, AlexanderLyNL commented on R/auditCommonFunctions.R
> +          boundLabel <- round(state[["ub"]], 3)
isn't upperBound more clear?

2021-10-06 10:17 UTC, AlexanderLyNL commented on R/auditCommonFunctions.R
> +      ub = qbeta(options[["conf_level"]], alphaPosterior, betaPosterior),
ciUpper

2021-10-06 10:30 UTC, AlexanderLyNL commented on R/auditCommonFunctionsBayesian.R
> +    table$addColumnInfo(name = "x", title = gettext("Equivalent errors"), type = "number")
Why is this named "x"?

2021-10-06 10:52 UTC, AlexanderLyNL commented on R/auditCommonFunctionsBayesian.R
> +    lb <- qgamma(conf_lb, shape = alpha, rate = beta)
ciLower

2021-10-06 19:05 UTC, merged