Actually use stringer.lta method
jasp-stats/jaspAudit pull request #220
Opened 2022-01-26 11:07 UTC by koenderks

2022-01-31 08:52 UTC, vandenman requested changes
Changes look fine, just a small question thing about the missing points.

2022-01-31 08:52 UTC, vandenman commented on tests/testthat/_snaps/auditbayesianplanning/prior-and-expected-posterior-distribution-1.svg
> -<circle cx='124.15' cy='481.54' r='5.12' style='stroke-width: 1.70; fill: #BEBEBE;' />
These two points are now missing in all the prior-and-expected-posterior plots. Is that intended?

2022-01-31 13:05 UTC, koenderks commented
@vandenman yes this is intended. These points should now only show in the prior and (not expected) posterior distribution plot

2022-02-03 14:25 UTC, vandenman approved these changes
both issues are fixed!

2022-02-03 14:25 UTC, merged