Add link to the manual to the help files
jasp-stats/jaspAudit pull request #52
Opened 2021-03-09 11:32 UTC by koenderks

2021-03-10 10:06 UTC, boutinb requested changes
This PR could be a good testcase for https://github.com/jasp-stats/jasp-actions/pull/3.
So if you are not in a hurry, let's wait that this action is implemented.

2021-03-10 10:06 UTC, boutinb commented on R/auditClassicalNumberBunching.R
> +    table$addColumnInfo(name = 'pvalue2', title = gettext("p"), 		type = 'pvalue', overtitle = gettext('Entropy'))
also these gettextf. I think you remove the gettext function

2021-03-10 10:06 UTC, boutinb commented on R/auditClassicalNumberBunching.R
> +    table$addColumnInfo(name = 'pvalue',	title = gettext("p"), 	type = 'pvalue')
Same here

2021-03-10 10:12 UTC, koenderks commented
To be honest, I would rather have it in the module now

2021-03-11 09:23 UTC, boutinb approved these changes

2021-03-11 09:23 UTC, merged